#!/bin/bash
# Builds everything:
# * HTML version of the Markdown documentation.
# * a linearized version of the Markdown documentation as a single document.
# * PFD version of the Markdown documentation as a single document.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

# parameters
args="$@"

"${script_dir}/generate" $args
"${script_dir}/generate-md-index" $args
"${script_dir}/linearize" $args
"${script_dir}/make_pdf" $args
"${script_dir}/make_html" $args

