#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Builds everything:
# * HTML version of the Markdown documentation.
# * a linearized version of the Markdown documentation as a single document.
# * PFD version of the Markdown documentation as a single document.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

# parameters
args=()
[ "$#" -gt 0 ] && args=("$@")

echo
echo "Building the documentation ..."
"$script_dir/print_versions"
"$script_dir/workarounds" "${args[@]}"
"$script_dir/generate" "${args[@]}"
"$script_dir/generate-md-index" "${args[@]}"
"$script_dir/linearize" "${args[@]}"
"$script_dir/make_pdf" "${args[@]}"
"$script_dir/make_html" "${args[@]}"
echo "Building the documentation done."

