#!/bin/bash
# Builds everything:
# * HTML version of the Markdown documentation.
# * a linearized version of the Markdown documentation as a single document.
# * PFD version of the Markdown documentation as a single document.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
. "${script_dir}/_common.sh"

"${script_dir}/generate"
"${script_dir}/generate-md-index"
"${script_dir}/linearize"
"${script_dir}/make_pdf"
"${script_dir}/make_html"

