#!/bin/sh
# Removes all build output.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir_rel=`dirname $0`
script_dir=`cd ${script_dir_rel}; pwd`
. "${script_dir}/_common.sh"

echo
echo "Cleaning the build directory ..."
rm -Rf "$build_dir"*

