#!/bin/bash
# Removes all build output.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

echo
echo "Cleaning the build directory ..."
rm -Rf "$build_dir"*

