#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generates sources, for example:
# * Markdown with PP (pandoc _p_re-_p_rocessor) instructions
#   -> Markdown
# * myDiagram.dot -> myDiagram.svg
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

# parameters
args=()
[ "$#" -gt 0 ] && args=("$@")

"$script_dir/gen-src-prepare" "${args[@]}"
_fetch_version > "$gen_src_dir/VERSION"
"$script_dir/pp-md"
#"$script_dir/gen-diagrams"

