#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2026 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# See the output of "$0 -h" for details.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
script_dir="$(dirname "$script_path")"
script_name="$(basename "$script_path")"
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

tools=()
#tools+=("jq") # for JSON parsing
_check_tools "${tools[@]}"
_check_env

# parameters
include_readme="${MVD_INCLUDE_README:-false}"

##################################################################
#{
#  "docs": {
#    "Guide": [
#      "01_Prepare.md"
#    ],
#    "images": [
#      "00_getting_started.md"
#    ],
#    "Guide": [
#      "02_Bla.md"
#    ]
#  }
#}
##################################################################

function print_help() {

	echo "$script_name - Creates an index of Markdown files"
	echo "from an FS-tree of Markdown files."
	echo
	echo "Usage:"
	echo "  $script_name [OPTIONS]"
	echo "Options:"
	echo "  -h, --help"
	echo "    Show this help message and exit"
	echo "  --mvd-include-readme"
	echo "    Include README*.md (case insensitive) in the output."
	echo "    Equivalent to (env var): MVD_INCLUDE_README=1"
	echo "Examples:"
	echo "  $script_name"
	echo "  $script_name --help"
}

# read command-line args
POSITIONAL=()
while [[ $# -gt 0 ]]
do
	arg="$1"
	shift # $2 -> $1, $3 -> $2, ...

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		--mvd-include-readme)
			include_readme=true
			;;
		--mvd-*)
			# Ignore this option; it is used in other MoVeDo scripts
			_movedo_common_arg_has_value "$arg" && shift
			;;
		*) # non-/unknown option
			POSITIONAL+=("$arg") # save it in an array for later
			;;
	esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

function index_txt2json() {
	in="$1"
	out="$2"

	cur_dir=""
	echo "{" > "$out"
	while read -d $'\n' -r entry
	do
		entry_dir=$(dirname "$entry")/
		entry_name=$(basename "$entry")

		while [[ "$entry_dir" == "$cur_dir"* ]]
		do
			# `cd ..`
			echo "},"
			cur_dir=$(echo "$cur_dir" | sed -e 's|[^/]*/$||')
		done

		remaining_path=$(echo "$entry_dir" | sed -e 's|^'$cur_dir'||')
		while [[ "$cur_dir" == "$entry_dir"* ]]
		do
			next_elem=$(echo "$remaining_path" | sed -e 's|/.*||')
			remaining_path=$(echo "$remaining_path" | sed -e 's|^[^/]+/||')
			# `cd $next_elem`
			echo "\"$next_elem\": {"
			cur_dir=$cur_dir/$next_elem
		done

		echo "\"$entry_name\": [],"
	done < "$in" > "${out}_tmp"
	# NOTE We use an intermediate file ("${out}_tmp"),
	#      because else we would lose the modification of variable `cur_dir`,
	#      due to using a pipe.
	jq '.' < "${out}_tmp" >> "$out"

	while [ -n "$cur_dir" ]
	do
		# `cd ..`
		echo "},"
		cur_dir=$(echo "$cur_dir" | sed -e 's|[^/]*/$||')
	done
}

function index_json2txt() {
	in="$1"
	out="$2"

	#TODO (use jq)
}

cd "$gen_src_dir"

# 1. find Markdown sources, excluding hidden directories (recursively)
#    and PP sources.
# 2. output "directory-dept file-path".
# 3. sort by these two, so deeper paths appear last,
#    resulting in Breadth First Traversal (BDT, or Level Order Traversal)
echo
echo "Generate index of Markdown sources on the basis of the file-system structure ..."
# HACK Ignoring "./movedo/*" might only be right for our specific (the default/intended) scenario.
find . \
	-type f \
	\( \
		-iname "*.md" \
		-o \
		-iname "*.markdown" \
	\) \
	\( ! -path "\./build/*" \) \
	\( ! -path "\./vendor/*" \) \
	\( ! -path "\./_vendor/*" \) \
	\( ! -path "\./themes/*" \) \
	\( ! -path "\./archetypes/*" \) \
	\( ! -ipath "\./movedo/*" \) \
	\( ! -iname "*.pp.md" \) \
	\( ! -regex '.*/\..*' \) \
	-printf "%d %p\0" \
		| sort -n --zero-terminated \
		| sed -z -e 's/^[0-9]\+\s//;' -e 's|^\./||' \
		| tr '\0' '\n' \
	> "$index_md_file_generated"

# Remove README*.md from the index, if requested (default).
if ! $include_readme
then
	mv "$index_md_file_generated" "${index_md_file_generated}_tmp"
	grep --invert-match --ignore-case "^README" \
		< "${index_md_file_generated}_tmp" \
		> "$index_md_file_generated"
	rm "${index_md_file_generated}_tmp"
fi
