#!/bin/sh
# Install the latest version of PP (a Pandoc pre-processor).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir_rel=`dirname "$0"`
script_dir=`cd "${script_dir_rel}"; pwd`
. "${script_dir}/_common.sh"

install_dir_pp="$HOME/.pp"
old_system=false

tools=""
tools="$tools git"
tools="$tools wget" # for getting a recent version of pp
_check_tools $tools

# install pp if not yet in PATH
if which pp > /dev/null 2>&1
then
	echo "'pp' is already installed."
else
	if [ -e "${install_dir_pp}/pp" ]
	then
		echo "'pp' already present."
	else
		echo "Installing 'pp' at '$install_dir_pp' ..."
		pre_dir=`pwd`
		mkdir -p "$install_dir_pp"
		cd "$install_dir_pp"
		if $old_system
		then
			# older systems (with GLIBC 2.29)
			archive="pp-linux-x86_64.txz"
			wget --quiet "https://cdsoft.fr/pp/$archive"
			tar vxf "$archive" pp > /dev/null
			rm "$archive"
		else
			# more recent systems
			wget --quiet --output-document=pp "https://fairkom.net/nextcloud/index.php/s/J5sLqJKtkGJkSE7/download"
		fi
		cd "$pre_dir"
	fi
	chmod +x "${install_dir_pp}/pp"
	_permanently_add_to_path "$install_dir_pp"
	echo "Done."
fi

# Check if `pp` can be found and log the version info
which pp
pp -v | sed -e 's/^/\t/' | head -n 1

