#!/bin/bash
# Install the latest version of mdBook (Static site generator written in Rust).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
. "${script_dir}/_common.sh"

tools=""
tools="$tools cargo" # for getting a recent version of mdbook
_check_tools $tools

#if [ ! -x "$HOME/.cargo/bin/cargo-install-update" ]
#then
#	echo "Installing 'cargo-update' (mdbook dependency) ..."
#	cargo install cargo-update
#fi

if [ ! -x "$HOME/.cargo/bin/mdbook" ]
then
	echo "Installing 'mdbook' ..."
	cargo install --vers "^0.2" mdbook
fi

#echo "Updating all cargo packages ..."
#cargo install-update -a

# Check if `pandoc` can be found
which mdbook
# ... and log the version info
mdbook -V | sed -e 's/^/\t/' | head -n 1 || true

