#!/bin/bash
# Install the latest version of pdsite (single BASH script static site generator).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

install_dir_pdsite="$HOME/.pdsite"

tools=""
tools="$tools git" # for getting a recent version of pdsite
_check_tools $tools

_update_pdsite() {
	echo "Updating 'pdsite' ..."
	pushd "$install_dir_pdsite"
	git pull --recurse-submodules
	popd
}

# install pdsite if not yet in PATH
if which pdsite > /dev/null 2>&1
then
	echo "'pdsite' is already installed."
	_update_pdsite
else
	if [ -e "${install_dir_pdsite}/bin/pdsite" ]
	then
		echo "'pdsite' already present."
		_update_pdsite
	else
		echo "Installing 'pdsite' at '$install_dir_pdsite' ..."
		git clone --recurse-submodules https://github.com/hoijui/pdsite "$install_dir_pdsite"
	fi
	chmod 744 "$install_dir_pdsite/bin/pdsite"
	_permanently_add_to_path "$install_dir_pdsite/bin"
	echo "Done."
fi

# Check if `pdsite` can be found and log the version info
which pdsite
pdsite -v | sed -e 's/^/\t/' | head -n 1

