#!/bin/bash
# Install the latest version of Panflute
# (a Python filter framework for the Pandoc Document type converter).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

tools=""
tools="$tools pip3" # for getting a recent version of panflute
_check_tools $tools

# parameters
args="$@"
including_locales=false
from_source=false
if [ "${LOCALES:-}" != "" ] || _contains_word "--locales" "$args"
then
	including_locales=true
	args="${args//--locales/}"
fi
if [ "${FROM_SOURCE:-}" != "" ] || _contains_word "--from-source" "$args"
then
	from_source=true
	args="${args//--from-source/}"
fi

if $including_locales
then
	# NOTE Required for panflute on python(2)
	echo "en_US UTF-8" > /etc/locale.gen
	locale-gen en_US.UTF-8
	{
		echo "export LANG=en_US.UTF-8"
		echo "export LANGUAGE=en_US:en"
		#echo "export LC_CTYPE=en_US.UTF-8"
		echo "export LC_ALL=en_US.UTF-8"
		echo "export PYTHONIOENCODING=utf8"
	} >> "$HOME/.bashrc"
	source "$HOME/.bashrc"
	source "$HOME/.profile"
fi

if [ "$from_source" = "true" ]
then
	prev_dir="$(pwd)"
	mkdir -p "$build_dir"
	cd "$build_dir"
	git clone "https://github.com/sergiocorreia/panflute.git"
	cd panflute
	python3 setup.py install
	cd "$prev_dir"
else
	pip3 install panflute
fi

# Check if `panflute` can be found
which panflute
# ... and log the version info
echo "import panflute; print(panflute.__version__)" \
	| python3 2> /dev/null \
	| sed -e 's/^/\t/' \
	| head -n 1 \
	|| true

