#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Install the latest version of mdBook (Static site generator written in Rust).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

tools=()
tools+=("cargo") # for getting a recent version of cargo, the rust build tool and package manager
_check_tools "${tools[@]}"

#if [ ! -x "$HOME/.cargo/bin/cargo-install-update" ]
#then
#	echo "Installing 'cargo-update' (mdbook dependency) ..."
#	cargo install cargo-update
#fi

if [ ! -x "$HOME/.cargo/bin/mdbook" ]
then
	echo "Installing 'mdbook' ..."
	cargo install --vers "^0.2" mdbook
fi

#echo "Updating all cargo packages ..."
#cargo install-update -a

# Check if it can be found
which mdbook
# ... and log the version info
mdbook -V | sed -e 's/^/\t/' | head -n 1 || true

