#!/bin/bash
# Install the latest version of Panflute
# (a Python filter framework for the Pandoc Document type converter).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
. "${script_dir}/_common.sh"

tools=""
tools="$tools pip3" # for getting a recent version of panflute
_check_tools $tools

including_locales=false
if [ "${1:-}" = "--locales" ]
then
	including_locales=true
fi

if $including_locales
then
	# NOTE Required for panflute on python(2)
	echo "en_US UTF-8" > /etc/locale.gen
	locale-gen en_US.UTF-8
	echo "export LANG=en_US.UTF-8" >> $HOME/.bashrc
	echo "export LANGUAGE=en_US:en" >> $HOME/.bashrc
	#echo "export LC_CTYPE=en_US.UTF-8" >> $HOME/.bashrc
	echo "export LC_ALL=en_US.UTF-8" >> $HOME/.bashrc
	echo "export PYTHONIOENCODING=utf8" >> $HOME/.bashrc
	. $HOME/.bashrc
	. $HOME/.profile
fi

pip3 install panflute

# Check if `panflute` can be found
which panflute
# ... and log the version info
echo "import panflute; print(panflute.__version__)" | python3 2> /dev/null \
	| sed -e 's/^/\t/' | head -n 1 || true

