#!/bin/bash
# Install the latest version of Pandoc (Document file type converter).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

tools=""
tools="$tools wget" # for getting a recent version of pandoc
_check_tools $tools

# parameters
args="$@"
pandoc_ver_required="${PANDOC_VERSION:-}"

if [ "${PANDOC_VERSION:-}" = "" ]
then
	pandoc_ver_latest=`wget -O - --max-redirect 0 https://github.com/jgm/pandoc/releases/latest 2>&1 | grep "Location:" | sed 's/.*\/tag\/\([^ "]*\).*/\1/'`
	pandoc_ver_required="$pandoc_ver_latest"
fi

# install pandoc if the latest version is not in PATH
pandoc_ver_installed=`which pandoc > /dev/null 2>&1 && pandoc -v | head -n 1 | sed -e 's/.* //' || echo "NONE"`
if [ "$pandoc_ver_installed" = "$pandoc_ver_required" ]
then
	echo "'pandoc' required version ($pandoc_ver_required) is already installed."
else
	echo "Installing pandoc $pandoc_ver_required ..."
	if `_is_deb`
	then
		pandoc_deb="pandoc-${pandoc_ver_required}-1-amd64.deb"
		wget --quiet "https://github.com/jgm/pandoc/releases/download/$pandoc_ver_required/$pandoc_deb"
		dpkg -i "$pandoc_deb"
		rm "$pandoc_deb"
	else
		pandoc_tgz="pandoc-${pandoc_ver_required}-linux.tar.gz"
		wget --quiet "https://github.com/jgm/pandoc/releases/download/$pandoc_ver_required/$pandoc_tgz"
		install_root=/usr/local
		#install_root=$HOME/.local
		tar xvzf "$pandoc_tgz" --strip-components 1 -C "$install_root"
		rm "$pandoc_tgz"
	fi
fi

# Check if `pandoc` can be found
which pandoc
# ... and log the version info
pandoc -v | sed -e 's/^/\t/' | head -n 1 || true

