#!/bin/bash
# Install WeasyPrint (HTML to PDF converter).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

tools=()
#tools+=("pip3") # for copying directory trees
_check_tools "${tools[@]}"

apt-get install -y -qq python3-pip libffi6 libffi-dev libcairo2 libpango-1.0-0 libpangocairo-1.0-0 > /dev/null
pip3 install pip cffi cairocffi WeasyPrint

# Check if `weasyprint` can be found
which weasyprint
# ... and log the version info
weasyprint --version | sed -e 's/^/\t/' | head -n 1 || true

