#!/bin/bash
# Install the latest version of Pandoc (Docuemnt file type converter).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
. "${script_dir}/_common.sh"

tools=""
tools="$tools wget" # for getting a recent version of pandoc
_check_tools $tools

# install pandoc if the latest version is not in PATH
pandoc_ver_inst=`which pandoc > /dev/null 2>&1 && pandoc -v | head -n 1 | sed -e 's/.* //' || echo "NONE"`
pandoc_ver_latest=`wget -O - --max-redirect 0 https://github.com/jgm/pandoc/releases/latest 2>&1 | grep "Location:" | sed 's/.*\/tag\/\([^ "]*\).*/\1/'`
if [ "$pandoc_ver_inst" = "$pandoc_ver_latest" ]
then
	echo "'pandoc' latest version ($pandoc_ver_latest) is already installed."
else
	echo "Installing pandoc $pandoc_ver_latest ..."
	if `_is_deb`
	then
		pandoc_deb="pandoc-${pandoc_ver_latest}-1-amd64.deb"
		wget --quiet "https://github.com/jgm/pandoc/releases/download/$pandoc_ver_latest/$pandoc_deb"
		dpkg -i "$pandoc_deb"
		rm "$pandoc_deb"
	else
		pandoc_tgz="pandoc-${pandoc_ver_latest}-linux.tar.gz"
		wget --quiet "https://github.com/jgm/pandoc/releases/download/$pandoc_ver_latest/$pandoc_tgz"
		install_root=/usr/local
		#install_root=$HOME/.local
		tar xvzf "$pandoc_tgz" --strip-components 1 -C "$install_root"
		rm "$pandoc_tgz"
	fi
fi

# Check if `pandoc` can be found and log the version info
which pandoc
pandoc -v | sed -e 's/^/\t/' | head -n 1 || true

