#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Install the latest version of mdBook
# (Static site generator written in Rust).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

tools=()
tools+=("cargo") # for getting a recent version of cargo, the rust build tool and package manager
_check_tools "${tools[@]}"

bin="mdbook"

#if [ ! -x "$HOME/.cargo/bin/cargo-install-update" ]
#then
#	echo "Installing 'cargo-update' ($bin dependency) ..."
#	cargo install cargo-update
#fi

if [ ! -x "$HOME/.cargo/bin/$bin" ]
then
	echo "Installing '$bin' ..."
	cargo install --vers "^0.2" "$bin"
fi

#echo "Updating all cargo packages ..."
#cargo install-update -a

# Check if it can be found
which "$bin"
# ... and log the version info
"$bin" --version | head -n 1 || true

