#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Install WeasyPrint
# (HTML to PDF converter).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

#tools=()
#tools+=("pip3") # for copying directory trees
#_check_tools "${tools[@]}"

bin="weasyprint"

apt-get install -y -qq python3-pip libffi6 libffi-dev libcairo2 libpango-1.0-0 libpangocairo-1.0-0 > /dev/null
pip3 install pip cffi cairocffi WeasyPrint

# Check if it can be found
which "$bin"
# ... and log the version info
"$bin" --version | head -n 1 || true

