#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Install the latest version of projvar (RROJect VARiables provider).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

tools=()
tools+=("wget") # for fetching what is the latest version of the tool
_check_tools "${tools[@]}"

# parameters
gh_slug="hoijui/projvar"
bin="projvar"
tool_ver_required="${MVD_PROJVAR_VERSION:-}"

"$script_dir/install_rust_gh_tool" \
	"$gh_slug" \
	"$bin" \
	"$tool_ver_required"

