#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2026 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# See the output of "$0 -h" for details.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
script_dir="$(dirname "$script_path")"
script_name="$(basename "$script_path")"
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

tools=()
tools+=("pandoc") # for Markdown filtering/cleanup
tools+=("python3") # for Panflute
tools+=("panflute") # for Pandoc filters
_check_tool "$script_dir/strip_front_matter"
_check_tools "${tools[@]}"
_check_env

# parameters
include_readme="${MVD_INCLUDE_README_IN_LINEARIZED:-false}"

function print_help() {

	echo "$script_name - Builds a single Markdown file"
	echo "out of an index of Markdown files."
	echo "We do that by using Pandoc with custom filters."
	echo
	echo "Usage:"
	echo "  $script_name [OPTIONS]"
	echo "Options:"
	echo "  -h, --help"
	echo "    Show this help message and exit"
	echo "  --mvd-include-readme-in-linearization"
	echo "    Include README*.md (case insensitive) in the linearized output."
	echo "    Equivalent to (env var): MVD_INCLUDE_README_IN_LINEARIZED=1"
	echo "Examples:"
	echo "  $script_name"
	echo "  $script_name --help"
}

# read command-line args
POSITIONAL=()
while [[ $# -gt 0 ]]
do
	arg="$1"
	shift # $2 -> $1, $3 -> $2, ...

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		--mvd-include-readme-in-linearization)
			include_readme=true
			;;
		--mvd-*)
			# Ignore this option; it is used in other MoVeDo scripts
			_movedo_common_arg_has_value "$arg" && shift
			;;
		*) # non-/unknown option
			POSITIONAL+=("$arg") # save it in an array for later
			;;
	esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

_debug "include_readme=$include_readme"

cd "$gen_src_dir"

rm -f "$single_md"

pandoc_extra=()
pandoc_extra+=("--citeproc")

function global_doc_meta() {
	if [ -f "$doc_meta_file" ]
	then
		doc_meta_file_gen="$gen_src_dir/$(basename "$doc_meta_file")"
		#	-e '/^#.*$/d' \
		sed \
			-i \
			-e '/^[-]\{3,\}$/d' \
			-e '/^[.]\{3,\}$/d' \
			"$doc_meta_file_gen"
		echo "---"
		echo "# HACK The first line after the above '---' needs to be a comment,"
		echo "#      or else this meta-data does not end up in the generated PDF,"
		echo "#      ... wierd!"
		cat "$doc_meta_file_gen"
		echo "---"
		echo
	fi
}

echo
echo "Generating single, linear Markdown file ..."

# This meta-data file is used for each markdown file to be converted,
# but only during conversion.
# We need this, as it is not possible to supply a YAML array
# with "-M" to pandoc, which we require for "panflute-filters".
common_lin_meta_file="$(mktemp --suffix=".yml")"
# Remove this file when script exits
trap 'rm -rf -- "$common_lin_meta_file"' EXIT
{
	echo "panflute-path: \"$filters_dir\""
	echo "panflute-filters: [add_local_link_prefix, normalize_links, linearize_links]"
	# Uncomment this next line for debugging
	# echo "panflute-verbose: true"
} > "$common_lin_meta_file"

rm -f "$index_md_file_linear"
if $include_readme
then
	ln -s "$index_md_file" "$index_md_file_linear"
else
	grep --invert-match --ignore-case "^README" \
		< "$index_md_file" \
		> "$index_md_file_linear"
fi

if [ "$(wc -l < "$index_md_file_linear")" -eq 1 ]
then
	# Build from a single source file
	md_in="$(cat "$index_md_file_linear")"
	single_md_tmp="${single_md}_tmp"
	rm -f "$single_md_tmp"
	# Use global document meta-data
	global_doc_meta >> "$single_md_tmp"
	# Use the single source file as-is
	cat "$md_in" >> "$single_md_tmp"
	echo "    adding '$md_in' ..."
	pandoc \
			--from=markdown \
			--to=markdown \
			--standalone \
			--markdown-headings=atx \
			-M allp_prefix="$(dirname "$md_in")/" \
			-M allp_file="$md_in" \
			-M ll_doc_path="" \
			--metadata-file="$common_lin_meta_file" \
			-F panflute \
			"${pandoc_extra[@]}" \
		< "$single_md_tmp" \
		>> "$single_md"
	rm "$single_md_tmp"
elif [ -f "$doc_meta_file" ]
then
	# Build from multiple source files

	# Use global document meta-data
	global_doc_meta >> "$single_md"
	while read -d $'\n' -r md_in
	do
		echo "Linearizing $md_in ..."
		if [ ! -e "$md_in" ]
		then
			_error "File '$md_in' not found! It is specified in the index file (for linearization) '$index_md_file_linear'."
		fi
		# TODO put this in its own script:
		# extract the document(-fragment)s title from the YAML meta-data
		grep "^title: " "$md_in" > /dev/null && {
			title=$(grep "^title: " "$md_in" \
				| head -n 1 \
				| sed -e 's/^title:[[:space:]]\+//')
			echo -e "# $title\n" >> "$single_md"
		}
		# here we do:
		# * strip front-matter
		# * cleanup
		# * filter
		#   * add_local_link_prefix
		#   * normalize_links
		#   * linearize_links
		# * write to the global document file
		echo "    adding '$md_in' ..."
		"$script_dir/strip_front_matter" "$md_in" \
			| pandoc \
				--from=markdown \
				--to=markdown \
				--markdown-headings=atx \
				-M allp_prefix="$(dirname "$md_in")/" \
				-M allp_file="$md_in" \
				-M ll_doc_path="$md_in" \
				--metadata-file="$common_lin_meta_file" \
				-F panflute \
				"${pandoc_extra[@]}" \
			>> "$single_md"
		echo -e "\n" >> "$single_md"
	done < "$index_md_file_linear"
else
	if [ "${MVD_SINGLE_FILE:-true}" = "true" ]
	then
		_error "If you have more then one source file, you need '$doc_meta_file', \
containing the YAML Front-Matter for the combined document, \
or you need to set the env var MVD_SINGLE_FILE to 'false'.
Your index (for linearization):
$(cat "$index_md_file_linear")"
	fi
fi

