#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Builds HTML out of Markdown files.
# We do that with `mdbook`.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

tools=()
tools+=("mdbook") # for Markdown to HTML conversion
_check_tools "${tools[@]}"
_check_env

# parameters
args=()
[ "$#" -gt 0 ] && args=("$@")

mdbook_extra=()
switch_next=false
for arg in "${args[@]}"
do
	if $switch_next
	then
		switch_next=false
		continue
	fi
	switch_next=false
	if ! _movedo_common_arg_is "$arg"
	then
		mdbook_extra+=("$arg")
	elif _movedo_common_arg_has_value "$arg"
	then
		switch_next=true
	fi
done

# mdbook requires a file called SUMMARY.md,
# containnig a markdown formatted index.
# We auto-create a simple version of it from the index-md file,
# if no SUMMARY.md is provided in the sources.
function generate_summary() {

	awk '{ printf "[%s](%s)\n\n", $0, $0; }' \
		< "$index_md_file" \
		> "$gen_src_dir_no_fm/SUMMARY.md" \
		|| exit 1
}

# HACK mdbook does not support (nor ignore) FrontMatter in MD files,
#      therefore we create a copy of the generated source files
#      and strip the FrontMatter there.
echo
echo "Stripping (YAML-)FrontMatter from MarkDown files (required for mdbook) ..."
gen_src_dir_no_fm="${gen_src_dir}_no_fm"
rm -Rf "$gen_src_dir_no_fm"
cp -r "$gen_src_dir" "$gen_src_dir_no_fm"
cd "$gen_src_dir_no_fm"
find . -type f -name "*.md" | while read -r md_src
do
	mvd strip_front_matter --in-place "$md_src"
done

echo
echo "Generating HTML (using mdbook) ..."

if [ ! -f "$proj_dir/SUMMARY.md" ]
then
	generate_summary
fi

mdbook build --dest-dir "$html_dir" "${mdbook_extra[@]}"
# NOTE This only tests rust code samples,
# and it assumes code snippets to be Rust,
# which is very disadventageous for a general content oriented framework
# like MoVeDo.
#mdbook test --dest-dir "$html_dir"

