#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Builds HTML out of a Markdown files.
# We do that with Pandoc, each source file separately.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

tools=()
tools+=("cpio") # for copying directory trees
tools+=("pandoc") # for per-file Markdown to HTML conversion
_check_tools "${tools[@]}"
_check_env

# parameters
args=()
[ "$#" -gt 0 ] && args=("$@")
copy_source_files=true
#template="bootstrap-template"
#template="bootstrap-adaptive-template"
#template="uikit"
#template="mdbook"
#template="mindoc"
#template=""
template="${HTML_TEMPLATE_NAME:-}"

cd "$gen_src_dir"

echo
echo "Generating HTML (using Pandoc native) ..."

echo "    Copy generated-sources *dir* structure to HTML output dir ..."
find . \
		-type d \
		\( ! -regex '.*/\..*' \) \
	| cpio -pdvm --quiet "${html_dir}" 2> /dev/null

if $copy_source_files
then
	echo "    Copy generated-sources *files* to HTML output dir ..."
	find . \
			-type f \
		| cpio -pdvm "${html_dir}" 2> /dev/null
fi

cd "${html_dir}"

echo "    Converting ..."

pandoc_extra=()
pandoc_extra+=("--citeproc")

if [ -e "$biblography_file" ]
then
	pandoc_extra+=("--bibliography=$biblography_file")
	pandoc_extra+=("--filter=pandoc-citeproc")
fi

switch_next=false
for arg in "${args[@]}"
do
	if $switch_next
	then
		switch_next=false
		continue
	fi
	switch_next=false
	if ! _movedo_common_arg_is "$arg"
	then
		pandoc_extra+=("$arg")
	elif _movedo_common_arg_has_value "$arg"
	then
		switch_next=true
	fi
done

if [ -n "$template" ]
then
	if [ -f "$templates_dir/pandoc-$template/standalone.html" ]
	then
		pandoc_extra+=("--template=$templates_dir/pandoc-$template/standalone.html")
	else
		pandoc_extra+=("--template=$templates_dir/pandoc-$template/template.html")
		pandoc_extra+=("--self-contained")
	fi
	if [ -f "$templates_dir/pandoc-$template/template.css" ]
	then
		css_file="pandoc-$template/template.css"
	fi
else
	css_file="pandoc-github.css"
fi
if [ -n "${css_file:-}" ]
then
	cp "$templates_dir/$css_file" "$html_dir/"
	pandoc_extra+=("--css=$css_file")
	# HACK for lazy devs ...
	pandoc_extra+=("--css=../$css_file")
	pandoc_extra+=("--css=../../$css_file")
	pandoc_extra+=("--css=../../../$css_file")
	pandoc_extra+=("--css=../../../../$css_file")
	pandoc_extra+=("--css=../../../../../$css_file")
	pandoc_extra+=("--css=../../../../../../$css_file")
	pandoc_extra+=("--css=../../../../../../../$css_file")
	pandoc_extra+=("--css=../../../../../../../../$css_file")
	pandoc_extra+=("--css=../../../../../../../../../$css_file")
	pandoc_extra+=("--css=../../../../../../../../../../$css_file")
fi

while read -r file_md
do
	if [ ! -e "$file_md" ]
	then
		_error "File '$file_md' not found! It is specified in the index file '$index_md_file'."
	fi
	html_file="${file_md%.md}.html"
	pandoc \
		--from=markdown \
		--to=html \
		--standalone \
		--markdown-headings=atx \
		--output="$html_file" \
		"${pandoc_extra[@]}" \
		"$file_md"
done < "$index_md_file"

