#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Builds a HTML out of a Markdown files.
# We do that with `pdsite`.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

tools=()
tools+=("pdsite") # for Markdown to HTML conversion
_check_tools "${tools[@]}"
_check_env

# parameters
args=()
[ "$#" -gt 0 ] && args=("$@")

cd "$gen_src_dir"

pdsite_extra=()
switch_next=false
for arg in "${args[@]}"
do
	if $switch_next
	then
		switch_next=false
		continue
	fi
	switch_next=false
	if ! _movedo_common_arg_is "$arg"
	then
		pdsite_extra+=("$arg")
	elif _movedo_common_arg_has_value "$arg"
	then
		switch_next=true
	fi
done

echo
echo "Generating HTML (using pdsite) ..."

pdsite build --output-folder "$html_dir" "${pdsite_extra[@]}"

