#!/bin/bash
# Builds a HTML out of a Markdown files.
# We do that with `pdsite`.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
. "${script_dir}/_common.sh"

tools=""
tools="$tools pdsite" # for Markdown to HTML conversion
_check_tools $tools
_check_env

cd "$gen_src_dir"

echo
echo "Generating HTML (using pdsite) ..."

pdsite build --output-folder "$html_dir" $@

