#!/bin/bash
# Builds a PDF out of a Markdown file.
# We do that with Pandoc.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
. "${script_dir}/_common.sh"

#h2p_tool=wkhtmltopdf
h2p_tool=weasyprint

_check_tool pandoc       # for Markdown ot HTML conversion
_check_tool $h2p_tool        # for HTML to PDF conversion
if [ "$h2p_tool" = "wkhtmltopdf" ] && $tool -h | grep "Reduced Functionality"
then
	_error "The version of 'wkhtmltopdf' found in the PATH does not support links in PDFs (among other things). Please install the static version instead."
fi
_check_env

# parameters
single_html="$pdf_dir/doc.html"

cd "$gen_src_dir"


echo
echo "Generating single HTML (Pandoc) ..."
mkdir -p "$pdf_dir"

pandoc_extra=()
pandoc_extra+=(--metadata=date:"`date -u '+%Y-%m-%d'`")

pandoc \
	--from=markdown \
	--to=html \
	--standalone \
	--atx-headers \
	--table-of-contents \
	--output="$single_html" \
	--css="$templates_dir/pandoc-github.css" \
	${pandoc_extra[*]} \
	$@ \
	"$single_md"

wkhtmltopdf_extra=()
wkhtmltopdf_extra+=(--page-size A4)
wkhtmltopdf_extra+=(--margin-bottom 20mm)
wkhtmltopdf_extra+=(--margin-top 20mm)
wkhtmltopdf_extra+=(--minimum-font-size 16)

weasyprint_extra=()
weasyprint_extra+=(--media-type=screen)
weasyprint_extra+=("--base-url=$gen_src_dir")

echo
echo "Generating single PDF ($h2p_tool) ..."
if [ "$h2p_tool" = "wkhtmltopdf" ]
then
	$h2p_tool \
		${wkhtmltopdf_extra[*]} \
		"$single_html" \
		"$single_pdf"
else
	if true
	then
		$h2p_tool \
			${weasyprint_extra[*]} \
			"$single_html" \
			"$single_pdf"
	else
		pandoc \
			--from=markdown \
			--to=html5 \
			--pdf-engine=weasyprint \
			--pdf-engine-opt=--presentational-hints \
			--pdf-engine-opt=--media-type=screen \
			--metadata link-citations=true \
			--webtex=https://latex.codecogs.com/svg.latex? \
			--css="$templates_dir/pandoc-github.css" \
			--output="$single_pdf" \
			"$single_md"
	fi
fi

