#!/bin/bash
# Builds a PDF out of a Markdown file.
# We do that with Pandoc.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
. "${script_dir}/_common.sh"

tools=""
tools="$tools pandoc" # for PDF generation
_check_tools $tools
_check_env

# parameters
h1_page_breaks=true

if _contains_word "--no-h1-page-breaks" "$@"
then
	h1_page_breaks=false
fi

cd "$gen_src_dir"

echo
echo "Generating PDF ..."
mkdir -p "$pdf_dir"

pandoc_extra=()
pandoc_extra+=(--metadata=date:"`date -u '+%Y-%m-%d'`")

if [ -e "$biblography_file" ]
then
	pandoc_extra+=("--bibliography=$biblography_file")
	pandoc_extra+=("--filter=pandoc-citeproc")
	#pandoc_extra="$pandoc_extra --bibliography $biblography_file --csl /home/hoijui/Projects/OSEG/repos/din_spec/chicago-fullnote-bibliography.csl --filter pandoc-citeproc"
	#pandoc_extra="$pandoc_extra --bibliography $biblography_file --csl /home/hoijui/Projects/OSEG/repos/din_spec/din-1505-2-alphanumeric.csl --filter pandoc-citeproc"
fi

if $h1_page_breaks
then
	# with this. Latex adds a page-break before every level 1 header
	pandoc_extra+=("--variable=documentclass:report")
fi

pandoc \
	--from=markdown \
	--to=latex \
	--standalone \
	--atx-headers \
	--table-of-contents \
	--output="$single_pdf" \
	${pandoc_extra[*]} \
	$@ \
	"$single_md"

