#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Builds HTML out of a Markdown files.
# We do that with Jekyll.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

tools=()
tools+=("pdsite") # for HTML site generation
tools+=("bundle") # for ruby package handling (jekyll)
tools+=("jekyll") # for HTML site generation
_check_tools "${tools[@]}"
_check_env

cd "$gen_src_dir"

echo
echo "Generating HTML (using Jekyll) ..."
bundle exec jekyll build --trace
mkdir -p "$html_dir"
rm -Rf "${html_dir:?}/"*
mv -f "$gen_src_dir/_site/"* "$html_dir/"
rmdir "$gen_src_dir/_site"

