#!/bin/bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Builds a HTML out of a Markdown files.
# How we try to do that depends on the client repos content.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

mkdir -p "$html_dir"
rm -Rf "${html_dir:?}/"*

# parameters
args=()
[ "$#" -gt 0 ] && args=("$@")

if [ -f "_config.yml" ]
then
	"$script_dir/make_html_jekyll" "${args[@]}"
elif [ -f "book.toml" ]
then
	"$script_dir/make_html_mdbook" "${args[@]}"
elif [ -f ".pdsite.yml" ]
then
	"$script_dir/make_html_pdsite" "${args[@]}"
else
	"$script_dir/make_html_pandoc" "${args[@]}"
fi

echo "HTML files generated under '$html_dir'"

if [ -n "$OPEN_X11" ] && [ -f "index.html" ]
then
	xdg-open "index.html"
fi

