#!/bin/bash
# Builds a HTML out of Markdown files.
# We do that with `mdbook`.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

tools=""
tools="$tools mdbook" # for Markdown to HTML conversion
_check_tools $tools
_check_env

# parameters
args="$@"

cd "$gen_src_dir"

# mdbook requires a file called SUMMARY.md,
# containnig a markdown formatted index.
# We auto-create a simple version of it from the index-md file,
# if no SUMMARY.md is provided in the sources.
function generate_summary() {

	cat "$index_md_file" \
		| awk '{ printf "[%s](%s)\n", $0, $0; }' \
		> "$gen_src_dir/SUMMARY.md"
}

echo
echo "Generating HTML (using mdbook) ..."

if [ ! -f "$proj_dir/SUMMARY.md" ]
then
	generate_summary
fi

mdbook build --dest-dir "$html_dir" $args
mdbook test --dest-dir "$html_dir"

