#!/bin/sh
# Builds a HTML out of a Markdown files.
# We do that with Jekyll.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir_rel=`dirname $0`
script_dir=`cd ${script_dir_rel}; pwd`
. "${script_dir}/_common.sh"

tools=""
#tools="$tools pdsite" # for HTML site generation
tools="$tools bundle" # for ruby package handling (jekyll)
tools="$tools jekyll" # for HTML site generation
_check_tools $tools
_check_env

cd "$gen_src_dir"

echo
echo "Generating HTML (using Jekyll) ..."
bundle exec jekyll build
mkdir -p "$html_dir"
rm -Rf "$html_dir/"*
mv -f "$gen_src_dir/_site/"* "$html_dir/"
rmdir "$gen_src_dir/_site"

