#!/bin/bash
# Builds a HTML out of Markdown files.
# We do that with `hugo`.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
. "${script_dir}/_common.sh"

tools=""
tools="$tools hugo" # for Markdown to HTML conversion
_check_tools $tools
_check_env

# parameters
args="$@"

cd "$gen_src_dir"

echo
echo "Generating HTML (using hugo) ..."

hugo --destination "$html_dir" $args

