#!/bin/bash
# Builds a HTML out of a Markdown files.
# We do that with Pandoc, each source file separately.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

tools=""
tools="$tools cpio" # for copying directory trees
tools="$tools pandoc" # for per-file Markdown to HTML conversion
_check_tools $tools
_check_env

# parameters
args="$@"
copy_source_files=true
version_as_subtitle=false
#template="bootstrap-template"
#template="bootstrap-adaptive-template"
#template="uikit"
#template="mdbook"
#template="mindoc"
#template=""
template="${HTML_TEMPLATE_NAME:-}"

if [ "${VERSION_AS_SUBTITLE:-}" != "" ] || _contains_word "--version-as-subtitle" "$args"
then
	version_as_subtitle=true
	args="${args//--version-as-subtitle/}"
fi

cd "$gen_src_dir"

echo
echo "Generating HTML (using Pandoc native) ..."

echo "    Copy generated-sources *dir* structure to HTML output dir ..."
find . \
		-type d \
		\( ! -regex '.*/\..*' \) \
	| cpio -pdvm --quiet "${html_dir}" 2> /dev/null

if $copy_source_files
then
	echo "    Copy generated-sources *files* to HTML output dir ..."
	find . \
			-type f \
		| cpio -pdvm "${html_dir}" 2> /dev/null
fi

cd "${html_dir}"

echo "    Converting ..."

pandoc_extra=()
doc_date="$(_fetch_document_date)"
pandoc_extra+=(--metadata=date:"$doc_date")
doc_version="$(_fetch_version)"
pandoc_extra+=(--metadata=version:"$doc_version")
if $version_as_subtitle
then
	pandoc_extra+=(--metadata=subtitle:$doc_version)
fi

if [ -e "$biblography_file" ]
then
	pandoc_extra+=("--bibliography=$biblography_file")
	pandoc_extra+=("--filter=pandoc-citeproc")
fi

if [ -n "$template" ]
then
	if [ -f "$movedo_root_dir/templates/pandoc-$template/standalone.html" ]
	then
		pandoc_extra+=("--template=$movedo_root_dir/templates/pandoc-$template/standalone.html")
	else
		pandoc_extra+=("--template=$movedo_root_dir/templates/pandoc-$template/template.html")
		pandoc_extra+=("--self-contained")
	fi
	if [ -f "$movedo_root_dir/templates/pandoc-$template/template.css" ]
	then
		pandoc_extra+=("--css=$movedo_root_dir/templates/pandoc-$template/template.css")
	fi
else
	pandoc_extra+=("--css=$templates_dir/pandoc-github.css")
fi

cat "$index_md_file" | while read -r md_file
do
	html_file=`echo $md_file | sed -e 's/\.md$/.html/'`
	pandoc \
		--from=markdown \
		--to=html \
		--standalone \
		--atx-headers \
		--output="$html_file" \
		"${pandoc_extra[@]}" \
		$args \
		"$md_file"
done

