#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Builds HTML out of Markdown files.
# We do that with `mdbook`.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

tools=()
tools+=("mdbook") # for Markdown to HTML conversion
_check_tools "${tools[@]}"
_check_env

# parameters
args=()
[ "$#" -gt 0 ] && args=("$@")

cd "$gen_src_dir"

mdbook_extra=()
switch_next=false
for arg in "${args[@]}"
do
	if $switch_next
	then
		switch_next=false
		continue
	fi
	switch_next=false
	if ! _movedo_common_arg_is "$arg"
	then
		mdbook_extra+=("$arg")
	elif _movedo_common_arg_has_value "$arg"
	then
		switch_next=true
	fi
done

# mdbook requires a file called SUMMARY.md,
# containnig a markdown formatted index.
# We auto-create a simple version of it from the index-md file,
# if no SUMMARY.md is provided in the sources.
function generate_summary() {

	awk '{ printf "[%s](%s)\n\n", $0, $0; }' \
		< "$index_md_file" \
		> "$gen_src_dir/SUMMARY.md" \
		|| exit 1
}

echo
echo "Generating HTML (using mdbook) ..."

if [ ! -f "$proj_dir/SUMMARY.md" ]
then
	generate_summary
fi

mdbook build --dest-dir "$html_dir" "${mdbook_extra[@]}"
# NOTE This only tests rust code samples,
# and it assumes code snippets to be Rust,
# which is very disadventageous for a general content oriented framework
# like MoVeDo.
#mdbook test --dest-dir "$html_dir"

