#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Prints the version of PanFlute that is currently installed.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "$script_dir/_common.sh"

python="$(which python || which python3)"
echo "import panflute; print(panflute.__version__)" \
	| "$python" 2> /dev/null \
	| sed -e 's/^/panflute /' \
	| head -n 1 \
	|| true
