#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Builds a HTML out of a Markdown files,
# and "serves" the result on a local HTTP server.
# We do that with Jekyll.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./_common.sh
. "${script_dir}/_common.sh"

tools=()
tools+=("pdsite") # for HTML site generation
tools+=("bundle") # for ruby package handling (jekyll)
tools+=("jekyll") # for HTML site generation
_check_tools "${tools[@]}"
_check_env

cd "$gen_src_dir"

echo
echo "Serving HTML ..."
bundle exec jekyll serve

