#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Strips YAML FrontMattter from a file
# (usually Markdown).
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See the LICENSES/ folder for copyright information.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Ee

script_name="$(basename "$0")"

print_help() {

	echo "Strips YAML FrontMattter from a file (usually Markdown)."
	echo
	echo "Usage:"
	echo "    $script_name -h"
	echo "    $script_name --help"
	echo "    $script_name -i <file-with-front-matter>"
	echo "    $script_name --in-place <file-with-front-matter>"
	echo "    $script_name <file-with-front-matter> <file-to-be-without-front-matter>"
}

replace=false
in_file="-"
out_file="/dev/stdout"

if [ -n "$1" ]
then
	if [ "$1" = "-h" ] || [ "$1" = "--help" ]
	then
		print_help
		exit 0
	elif [ "$1" = "-i" ] || [ "$1" = "--in-place" ]
	then
		replace=true
		in_file="$2"
		out_file="$in_file"
	else
		in_file="$1"
		if [ -n "$2" ]
		then
			out_file="$2"
		fi
	fi
fi

tmp_out_file="$out_file"
if $replace
then
	tmp_out_file="${in_file}_tmp"
fi

awk '
BEGIN {
	is_first_line=1;
	in_fm=0;
}
/^---$/ {
	if (is_first_line) {
		in_fm=1;
	}
}
{
	if (! in_fm) {
		print $0;
	}
}
/^(---|...)$/ {
	if (! is_first_line) {
		in_fm=0;
	}
	is_first_line=0;
}
' "$in_file" >> "$tmp_out_file"

if $replace
then
	mv "$tmp_out_file" "$out_file"
fi

