#!/bin/sh
# Builds a HTML out of a Markdown files,
# and "serves" the result on a local HTTP server.
# We do that with Jekyll.
#
# This is part of the [MoVeDo](https://github.com/movedo) project.
# See LICENSE.md for copyright information.

script_dir_rel=`dirname $0`
script_dir=`cd ${script_dir_rel}; pwd`
. "${script_dir}/_common.sh"

tools=""
#tools="$tools pdsite" # for HTML site generation
tools="$tools bundle" # for ruby package handling (jekyll)
tools="$tools jekyll" # for HTML site generation
_check_tools $tools
_check_env

cd "$gen_src_dir"

echo
echo "Serving HTML ..."
bundle exec jekyll serve

